### ISSUE TITLE
我在微软商店安装了软件，但是打不开，vc库已经安装了

### ISSUE THREAD

**Issue by yvfubp** [Ebola-Chan-bot/Automatically-change-local-desktop-lock-screen-wallpaper#4]
系统日志：
错误应用程序名称: 桌面锁屏自动换.exe，版本: 1.0.0.0，时间戳: 0x6514d416
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.4717，时间戳: 0x16b0a901
异常代码: 0xe0434352
错误偏移量: 0x000000000003b699
错误进程 ID: 0x8dc
错误应用程序启动时间: 0x01daf45ca83ac897
错误应用程序路径: C:\Program Files\WindowsApps\4264644686220.6993758F38F5_1.0.3.0_x64__4xb3727f2dd7j\桌面锁屏自动换\桌面锁屏自动换.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 76e33a49-2657-4051-8f5f-2a708b37a419
错误程序包全名: 4264644686220.6993758F38F5_1.0.3.0_x64__4xb3727f2dd7j
错误程序包相对应用程序 ID: App

**Comment by yvfubp** [comment]
Application: 桌面锁屏自动换.exe
CoreCLR Version: 7.0.1223.47720
.NET Version: 7.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at 本地桌面锁屏壁纸自动换.MainWindow.更新当前锁屏()
   at 本地桌面锁屏壁纸自动换.MainWindow..ctor()
   at 本地桌面锁屏壁纸自动换.Application.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at 本地桌面锁屏壁纸自动换.Application.Main()

**Comment by yvfubp** [comment]
可以打开了，显示一个白框，然后就关闭了

Application: 桌面锁屏自动换.exe
CoreCLR Version: 9.0.24.40507
.NET Version: 9.0.0-preview.7.24405.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at 本地桌面锁屏壁纸自动换.MainWindow.更新当前锁屏()
   at 本地桌面锁屏壁纸自动换.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

错误应用程序名称: 桌面锁屏自动换.exe，版本: 1.0.0.0，时间戳: 0x66b10000
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.4717，时间戳: 0x16b0a901
异常代码: 0xe0434352
错误偏移量: 0x000000000003b699
错误进程 ID: 0x2294
错误应用程序启动时间: 0x01daf9772f82d813
错误应用程序路径: C:\Program Files\WindowsApps\4264644686220.6993758F38F5_1.0.4.0_x64__4xb3727f2dd7j\桌面锁屏自动换\桌面锁屏自动换.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: c91190d5-62d5-4d78-9569-ef191c00d0f3
错误程序包全名: 4264644686220.6993758F38F5_1.0.4.0_x64__4xb3727f2dd7j
错误程序包相对应用程序 ID: App

**Comment by yvfubp** [comment]
错误应用程序名称: 桌面锁屏自动换.exe，版本: 1.0.0.0，时间戳: 0x66b10000
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.4717，时间戳: 0x16b0a901
异常代码: 0xe0434352
错误偏移量: 0x000000000003b699
错误进程 ID: 0x728
错误应用程序启动时间: 0x01daf9dd5f0dd330
错误应用程序路径: C:\Program Files\WindowsApps\4264644686220.6993758F38F5_1.0.5.0_x64__4xb3727f2dd7j\桌面锁屏自动换\桌面锁屏自动换.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 9cc589c2-a570-42c9-a8e1-aa2e8ebcc701
错误程序包全名: 4264644686220.6993758F38F5_1.0.5.0_x64__4xb3727f2dd7j
错误程序包相对应用程序 ID: App

Application: 桌面锁屏自动换.exe
CoreCLR Version: 9.0.24.40507
.NET Version: 9.0.0-preview.7.24405.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.行号：6
   at 本地桌面锁屏壁纸自动换.MainWindow.更新当前锁屏()
   at 本地桌面锁屏壁纸自动换.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by yvfubp** [comment]
AuthenticationType : NTLM
ImpersonationLevel : None
IsAuthenticated    : True
IsGuest            : False
IsSystem           : False
IsAnonymous        : False
Name               : DESKTOP-I9ITVUT\xt
Owner              : S-1-5-21-3874940317-2832438638-1831967602-1001
User               : S-1-5-21-3874940317-2832438638-1831967602-1001
Groups             : {S-1-5-21-3874940317-2832438638-1831967602-513, S-1-1-0, S-1-5-32-559, S-1-5-32-545...}
Token              : 3036
AccessToken        : Microsoft.Win32.SafeHandles.SafeAccessTokenHandle
UserClaims         : {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: DESKTOP-I9ITVUT\xt, http://schemas.mi
                     crosoft.com/ws/2008/06/identity/claims/primarysid: S-1-5-21-3874940317-2832438638-1831967602-1001,
                      http://schemas.microsoft.com/ws/2008/06/identity/claims/primarygroupsid: S-1-5-21-3874940317-2832
                     438638-1831967602-513, http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid: S-1-5-21-
                     3874940317-2832438638-1831967602-513...}
DeviceClaims       : {}
Claims             : {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: DESKTOP-I9ITVUT\xt, http://schemas.mi
                     crosoft.com/ws/2008/06/identity/claims/primarysid: S-1-5-21-3874940317-2832438638-1831967602-1001,
                      http://schemas.microsoft.com/ws/2008/06/identity/claims/primarygroupsid: S-1-5-21-3874940317-2832
                     438638-1831967602-513, http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid: S-1-5-21-
                     3874940317-2832438638-1831967602-513...}
Actor              :
BootstrapContext   :
Label              :
NameClaimType      : http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
RoleClaimType      : http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid

**Comment by yvfubp** [comment]
S-1-5-21-3874940317-2832438638-1831967602-1001

错误应用程序名称: 桌面锁屏自动换.exe，版本: 1.0.0.0，时间戳: 0x66b10000
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.4717，时间戳: 0x16b0a901
异常代码: 0xe0434352
错误偏移量: 0x000000000003b699
错误进程 ID: 0x38bc
错误应用程序启动时间: 0x01dafae9b887f649
错误应用程序路径: C:\Program Files\WindowsApps\4264644686220.6993758F38F5_1.0.6.0_x64__4xb3727f2dd7j\桌面锁屏自动换\桌面锁屏自动换.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 4bb8a01a-e8e1-440c-a86d-8718b41811bc
错误程序包全名: 4264644686220.6993758F38F5_1.0.6.0_x64__4xb3727f2dd7j
错误程序包相对应用程序 ID: App

Application: 桌面锁屏自动换.exe
CoreCLR Version: 9.0.24.40507
.NET Version: 9.0.0-preview.7.24405.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at 本地桌面锁屏壁纸自动换.MainWindow.更新当前锁屏()
   at 本地桌面锁屏壁纸自动换.MainWindow..ctor()
   at 本地桌面锁屏壁纸自动换.Application.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at 本地桌面锁屏壁纸自动换.Application.Main()

**Comment by yvfubp** [comment]
Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPCODE_VM_OPTIONS             D:\jetbra\vmoptions\appcode.vmoptions
APPDATA                        C:\Users\xt\AppData\Roaming
CLion                          D:\CLion 2023.2\bin;
CLION_VM_OPTIONS               D:\jetbra\vmoptions\clion.vmoptions
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   DESKTOP-I9ITVUT
ComSpec                        C:\Windows\system32\cmd.exe
DATAGRIP_VM_OPTIONS            D:\jetbra\vmoptions\datagrip.vmoptions
DATASPELL_VM_OPTIONS           D:\jetbra\vmoptions\dataspell.vmoptions
DEVECOSTUDIO_VM_OPTIONS        D:\jetbra\vmoptions\devecostudio.vmoptions
DriverData                     C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING Internet Explorer
FPS_BROWSER_USER_PROFILE_ST... Default
GATEWAY_VM_OPTIONS             D:\jetbra\vmoptions\gateway.vmoptions
GOLAND_VM_OPTIONS              D:\jetbra\vmoptions\goland.vmoptions
HOMEDRIVE                      C:
HOMEPATH                       \Users\xt
IDEA_VM_OPTIONS                D:\jetbra\vmoptions\idea.vmoptions
IntelliJ IDEA                  D:\IntelliJ IDEA 2023.3.3\bin;
JETBRAINS_CLIENT_VM_OPTIONS    D:\jetbra\vmoptions\jetbrains_client.vmoptions
JETBRAINSCLIENT_VM_OPTIONS     D:\jetbra\vmoptions\jetbrainsclient.vmoptions
LOCALAPPDATA                   C:\Users\xt\AppData\Local
LOGONSERVER                    \\DESKTOP-I9ITVUT
NUMBER_OF_PROCESSORS           12
OneDrive                       C:\Users\xt\OneDrive - sunxyzoffice
OS                             Windows_NT
Path                           C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPo...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PHPSTORM_VM_OPTIONS            D:\jetbra\vmoptions\phpstorm.vmoptions
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
PROCESSOR_LEVEL                25
PROCESSOR_REVISION             2102
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSModulePath                   C:\Users\xt\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Mo...
PUBLIC                         C:\Users\Public
PyCharm                        D:\PyCharm 2024.1.1\bin;
PYCHARM_VM_OPTIONS             D:\jetbra\vmoptions\pycharm.vmoptions
RIDER_VM_OPTIONS               D:\jetbra\vmoptions\rider.vmoptions
RUBYMINE_VM_OPTIONS            D:\jetbra\vmoptions\rubymine.vmoptions
SESSIONNAME                    Console
STUDIO_VM_OPTIONS              D:\jetbra\vmoptions\studio.vmoptions
SystemDrive                    C:
SystemRoot                     C:\Windows
TEMP                           C:\Users\xt\AppData\Local\Temp
TMP                            C:\Users\xt\AppData\Local\Temp
USERDOMAIN                     DESKTOP-I9ITVUT
USERDOMAIN_ROAMINGPROFILE      DESKTOP-I9ITVUT
USERNAME                       xt
USERPROFILE                    C:\Users\xt
WEBIDE_VM_OPTIONS              D:\jetbra\vmoptions\webide.vmoptions
WEBSTORM_VM_OPTIONS            D:\jetbra\vmoptions\webstorm.vmoptions
windir                         C:\Windows

C:\ProgramData

C:

**Comment by yvfubp** [comment]
4在哪？
![屏幕截图 2024-09-02 000530](https://github.com/user-attachments/assets/bc576254-47e4-442a-b9ab-0ec74ba9ffac)
